# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
	config.vbguest.auto_update = false
	config.vbguest.no_remote = true
  # config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Debian_Jessie64"
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
